# Generated by Django 3.2.9 on 2021-11-10 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='field',
            field=models.JSONField(verbose_name='Хитрое JSON поле'),
        ),
    ]
